version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      retries: 5

  productservice:
    build:
      context: ../
      dockerfile: services/productservice/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ../services/productservice/.env
    depends_on:
      postgres:
        condition: service_healthy

  userservice:
    build:
      context: ../
      dockerfile: services/userservice/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ../services/userservice/.env
    depends_on:
      postgres:
        condition: service_healthy

  orderservice:
    build:
      context: ../
      dockerfile: services/orderservice/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ../services/orderservice/.env
    depends_on:
      postgres:
        condition: service_healthy
